/** @type {import('tailwindcss').Config} */
const { steelBlueTheme, modernBlueTheme, darkSlateTheme } = require("./constants/theme");

module.exports = {
  content: ["./index.js", "./App.js", "./src/**/*.{js,jsx,ts,tsx}", "./components/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        // Steel Blue theme colors
        "steelBlue-appBg": steelBlueTheme.colors.appBg,
        "steelBlue-primary": steelBlueTheme.colors.primary,
        "steelBlue-secondary": steelBlueTheme.colors.secondary,
        "steelBlue-accent": steelBlueTheme.colors.accent,
        "steelBlue-danger": steelBlueTheme.colors.danger,
        "steelBlue-success": steelBlueTheme.colors.success,
        "steelBlue-headingText": steelBlueTheme.colors.headingText,
        "steelBlue-subHeadingText": steelBlueTheme.colors.subHeadingText,
        "steelBlue-bodyText": steelBlueTheme.colors.bodyText,
        "steelBlue-headerBg": steelBlueTheme.colors.headerBg,
        "steelBlue-headerText": steelBlueTheme.colors.headerText,
        "steelBlue-inputBg": steelBlueTheme.colors.inputBg,
        "steelBlue-inputBorder": steelBlueTheme.colors.inputBorder,
        "steelBlue-inputText": steelBlueTheme.colors.inputText,
        "steelBlue-inputPlaceholder": steelBlueTheme.colors.inputPlaceholder,
        "steelBlue-cardBg": steelBlueTheme.colors.cardBg,
        "steelBlue-cardBorder": steelBlueTheme.colors.cardBorder,
        "steelBlue-cardHeading": steelBlueTheme.colors.cardHeading,
        "steelBlue-cardText": steelBlueTheme.colors.cardText,
        "steelBlue-buttonPrimaryBg": steelBlueTheme.colors.buttonPrimaryBg,
        "steelBlue-buttonPrimaryText": steelBlueTheme.colors.buttonPrimaryText,
        "steelBlue-buttonSecondaryBg": steelBlueTheme.colors.buttonSecondaryBg,
        "steelBlue-buttonSecondaryText": steelBlueTheme.colors.buttonSecondaryText,
        "steelBlue-buttonSecondaryBorder": steelBlueTheme.colors.buttonSecondaryBorder,
        "steelBlue-buttonDangerBg": steelBlueTheme.colors.buttonDangerBg,
        "steelBlue-buttonDangerText": steelBlueTheme.colors.buttonDangerText,
        "steelBlue-buttonDisabledBg": steelBlueTheme.colors.buttonDisabledBg,
        "steelBlue-buttonDisabledText": steelBlueTheme.colors.buttonDisabledText,

        // Modern Blue theme colors
        "modernBlue-appBg": modernBlueTheme.colors.appBg,
        "modernBlue-primary": modernBlueTheme.colors.primary,
        "modernBlue-secondary": modernBlueTheme.colors.secondary,
        "modernBlue-accent": modernBlueTheme.colors.accent,
        "modernBlue-danger": modernBlueTheme.colors.danger,
        "modernBlue-success": modernBlueTheme.colors.success,
        "modernBlue-headingText": modernBlueTheme.colors.headingText,
        "modernBlue-subHeadingText": modernBlueTheme.colors.subHeadingText,
        "modernBlue-bodyText": modernBlueTheme.colors.bodyText,
        "modernBlue-headerBg": modernBlueTheme.colors.headerBg,
        "modernBlue-headerText": modernBlueTheme.colors.headerText,
        "modernBlue-inputBg": modernBlueTheme.colors.inputBg,
        "modernBlue-inputBorder": modernBlueTheme.colors.inputBorder,
        "modernBlue-inputText": modernBlueTheme.colors.inputText,
        "modernBlue-inputPlaceholder": modernBlueTheme.colors.inputPlaceholder,
        "modernBlue-cardBg": modernBlueTheme.colors.cardBg,
        "modernBlue-cardBorder": modernBlueTheme.colors.cardBorder,
        "modernBlue-cardHeading": modernBlueTheme.colors.cardHeading,
        "modernBlue-cardText": modernBlueTheme.colors.cardText,
        "modernBlue-buttonPrimaryBg": modernBlueTheme.colors.buttonPrimaryBg,
        "modernBlue-buttonPrimaryText": modernBlueTheme.colors.buttonPrimaryText,
        "modernBlue-buttonSecondaryBg": modernBlueTheme.colors.buttonSecondaryBg,
        "modernBlue-buttonSecondaryText": modernBlueTheme.colors.buttonSecondaryText,
        "modernBlue-buttonSecondaryBorder": modernBlueTheme.colors.buttonSecondaryBorder,
        "modernBlue-buttonDangerBg": modernBlueTheme.colors.buttonDangerBg,
        "modernBlue-buttonDangerText": modernBlueTheme.colors.buttonDangerText,
        "modernBlue-buttonDisabledBg": modernBlueTheme.colors.buttonDisabledBg,
        "modernBlue-buttonDisabledText": modernBlueTheme.colors.buttonDisabledText,

        // Dark Slate theme colors
        "darkSlate-appBg": darkSlateTheme.colors.appBg,
        "darkSlate-primary": darkSlateTheme.colors.primary,
        "darkSlate-secondary": darkSlateTheme.colors.secondary,
        "darkSlate-accent": darkSlateTheme.colors.accent,
        "darkSlate-danger": darkSlateTheme.colors.danger,
        "darkSlate-success": darkSlateTheme.colors.success,
        "darkSlate-headingText": darkSlateTheme.colors.headingText,
        "darkSlate-subHeadingText": darkSlateTheme.colors.subHeadingText,
        "darkSlate-bodyText": darkSlateTheme.colors.bodyText,
        "darkSlate-headerBg": darkSlateTheme.colors.headerBg,
        "darkSlate-headerText": darkSlateTheme.colors.headerText,
        "darkSlate-inputBg": darkSlateTheme.colors.inputBg,
        "darkSlate-inputBorder": darkSlateTheme.colors.inputBorder,
        "darkSlate-inputText": darkSlateTheme.colors.inputText,
        "darkSlate-inputPlaceholder": darkSlateTheme.colors.inputPlaceholder,
        "darkSlate-cardBg": darkSlateTheme.colors.cardBg,
        "darkSlate-cardBorder": darkSlateTheme.colors.cardBorder,
        "darkSlate-cardHeading": darkSlateTheme.colors.cardHeading,
        "darkSlate-cardText": darkSlateTheme.colors.cardText,
        "darkSlate-buttonPrimaryBg": darkSlateTheme.colors.buttonPrimaryBg,
        "darkSlate-buttonPrimaryText": darkSlateTheme.colors.buttonPrimaryText,
        "darkSlate-buttonSecondaryBg": darkSlateTheme.colors.buttonSecondaryBg,
        "darkSlate-buttonSecondaryText": darkSlateTheme.colors.buttonSecondaryText,
        "darkSlate-buttonSecondaryBorder": darkSlateTheme.colors.buttonSecondaryBorder,
        "darkSlate-buttonDangerBg": darkSlateTheme.colors.buttonDangerBg,
        "darkSlate-buttonDangerText": darkSlateTheme.colors.buttonDangerText,
        "darkSlate-buttonDisabledBg": darkSlateTheme.colors.buttonDisabledBg,
        "darkSlate-buttonDisabledText": darkSlateTheme.colors.buttonDisabledText,
      },
      fontSize: {
        xs: ["12px", { lineHeight: "16px" }],
        sm: ["14px", { lineHeight: "20px" }],
        base: ["16px", { lineHeight: "24px" }],
        lg: ["18px", { lineHeight: "28px" }],
        xl: ["20px", { lineHeight: "28px" }],
        "2xl": ["24px", { lineHeight: "32px" }],
        "3xl": ["30px", { lineHeight: "36px" }],
        "4xl": ["36px", { lineHeight: "40px" }],
        "5xl": ["48px", { lineHeight: "1" }],
        "6xl": ["60px", { lineHeight: "1" }],
      },
    },
  },
  plugins: [],
};
